### ISSUE TITLE
Take away Custom Enchants from Armor or  Weapons

### ISSUE THREAD

**Issue by kokoPvP** [LorgeN/CrazyWars-Issues#101]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I put on a custom enchant, and then I realize I should have put a different custom enchant.

**Describe the solution you'd like**
The solution I'd like is when you put on the wrong custom enchant and you can go to the Blacksmith or the Wizard Tower and get it taken off.

**Describe alternatives you've considered**
I would just like you to be able to go to  building like the Blacksmith or Wizard Tower to take off a custom enchant.

**Comment by TomIsTheHunter** [comment]
In addition to this, I think it would make PVP slightly more rewarding with being able to kill people and steal their enchantments for your own personal use.

**Comment by MemelordGod** [comment]
I also think this would be a good idea. It would also be fairly easy to implement, especially if you design the device after Minecraft 1.14+'s Grindstone.
