### ISSUE TITLE
My Island is doing weird things and i dont like it...

### ISSUE THREAD

**Issue by ArceusFoxx** [LorgeN/CrazyWars-Issues#104]
ArceusFoxx

Skyblock Island

Unsure

The wool on my husbands statue's feet keeps disappearing a couple days after its placed, grass blocks are reverting to dirt blocks, and now i cant plant potatoes in a certain spot on my farm

I expect Blocks to stay where i put them and to be able to farm without any issues

**Screenshots/Videos**
![2019-10-31_20 48 15](https://user-images.githubusercontent.com/56695045/67997064-53682d00-fc20-11e9-9772-75d4e87d6689.png)

I am concerned that my Island may Bug out like Mixeq's did and i lose it all, if that happens my husband will get discouraged and quit the server, this is a big deal to me cause this is how me and him spend time together and i dont want to lose that.

**Comment by ArceusFoxx** [comment]
The potatoes are Acting like cacti they cant be planted next to each other, but can be placed diagonally

**Comment by LorgeN** [comment]
Are you sure you have the correct light levels, and that you do not have any island members that are making these changes? Wool can also burn. None of this is fixable because there is no bug that can cause this.
