### ISSUE TITLE
Player plot coordinates command

### ISSUE THREAD

**Issue by TomIsTheHunter** [LorgeN/CrazyWars-Issues#105]
**Is your feature request related to a problem? Please describe.**
/playerinfo doesn't show users plots/plot coordinates

**Describe the solution you'd like**
I would like /playerinfo command to show all owned coordinates to plots 

**Describe alternatives you've considered**
I would assume an alternative command /plots [username] would work just as well. With potentially the additional bonus of not spamming /playerinfo with lots of coordinates (if they have lots of plots)

**Additional context**
This afternoon I encountered a user making lag machines, Wondering if the user had made others I wanted to investigate they alterative plots

**Comment by LorgeN** [comment]
/playerinfo is a core command, not a creative plots command.
