### ISSUE TITLE
Visual Glitch Experience Tank

### ISSUE THREAD

**Issue by zulater** [LorgeN/CrazyWars-Issues#11]
**Minecraft Username**
zulater

**What is this about?**
Skyblock Experience Ed

**To Reproduce**
Filled XP Tank, then upgraded and filled again

**What happens?**
Visual glitch with hologram duplicating old and new %

**What should happen?**
Only show new

**Screenshots/Videos**
Attached
![2019-09-09_23 11 44](https://user-images.githubusercontent.com/55066513/64583674-73cde680-d357-11e9-8b3b-204653e5be28.png)

**Comment by LorgeN** [comment]
Fixed in https://github.com/LorgeN/CrazyWars/commit/0ee8dec6519d11e1ef7120b34ce843e55f92e54d, removed NPC and added button (Both as a block and in the menu)
