### ISSUE TITLE
Minecraft username: Xvxa

### ISSUE THREAD

**Issue by Xvxa** [LorgeN/CrazyWars-Issues#114]
**Minecraft Username**
Your Minecraft username

**What is this about?**
E. g. SkyBlock Islands

**To Reproduce**
Steps to reproduce the behavior

**What happens?**
What happens when you do this

**What should happen?**

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**

**Comment by wzhouruize** [comment]
What even is this? Are you trolling?

**Comment by MemelordGod** [comment]
wzhouruize Please try to keep your comments in this field relevant.
