### ISSUE TITLE
Item transporter drops items when transporting to a full chest

### ISSUE THREAD

**Issue by wzhouruize** [LorgeN/CrazyWars-Issues#117]
**Minecraft Username**
Anachronistical

**What is this about?**
Islands

**To Reproduce**
Set the item consumer to a full chest from an item transporter.

**What happens?**
The items are spit out onto the ground and quickly despawn.

**What should happen?**
The items should not be transferred and stay in the item producer.

**Screenshots/Videos**
Video of the bug: https://www.youtube.com/watch?v=T8VP33XqALs

**Additional context**
Issue originally reported to me by SnickersThePony. A couple players have lost items due to this bug, and I'm not sure if it's intentional or the items just don't have anywhere to go and are rejected by the chest and dropped on the ground.

**Comment by LorgeN** [comment]
This is not a bug. It is intentional.
