### ISSUE TITLE
Free XP from buildings already placed

### ISSUE THREAD

**Issue by zulater** [LorgeN/CrazyWars-Issues#12]
**Minecraft Username**
ParkourM4ster (zualter reporting)

**What is this about?**
Skyblock

**To Reproduce**
Player just logs in and buildings already placed are "re-placing" (like the old chat spam from buildings) but also rewarding xp.

**What happens?**
Free XP

**What should happen?**
Nothing, building already placed and XP already rewarded

**Screenshots/Videos**
N/A but could get one if needed

**Comment by zulater** [comment]
![image](https://user-images.githubusercontent.com/55066513/64662380-d84b7d00-d40d-11e9-8225-d822d1603aac.png)
![image](https://user-images.githubusercontent.com/55066513/64662393-e7cac600-d40d-11e9-937a-9109cb0d2657.png)
Notice the level up.  This was when he just joined, did nothing else.

**Comment by zulater** [comment]
Additionally,  ParkourM4ster believes they are getting applied when the server reboots (just happened again).  It does not happen when he logs off and back on.

**Comment by LorgeN** [comment]
Should potentially be fixed once I push the new saving system for buildings

**Comment by LorgeN** [comment]
@zulater Any reports of this still happening?

**Comment by zulater** [comment]
I do not believe so. Close till we hear more.
