### ISSUE TITLE
Armor Repair Options 

### ISSUE THREAD

**Issue by Mixeq** [LorgeN/CrazyWars-Issues#122]
**Is your feature request related to a problem? Please describe.**
High tier items only keep their value until they are broken, and no amount of money can repair them. This is frustrating because people cannot keep their high tier items, such as prot 10 armor or tier 5 crate armor.

**Describe the solution you'd like**
I think items should be able to be repaired with no chance of enchantment loss at spawn via a sign. Right-clicking this sign would charge 1.5 million tokens, but completely restore the durability of an item.

**Describe alternatives you've considered**
Advertising to players that you can ask an admin to repair items in exchange for tokens

**Additional context**
The reason that the price is so high is to make repairing items very difficult to do. This will prevent players from repairing items super often, even someone with a lot of tokens would take a significant hit each time they repair a set of armor. (6 million tokens)
I know that the p10 kit is being buffed for this reason, but I think there needs to be an option to repair armor in some way, even if it costs a significant amount of tokens.
[Some of this content was suggested by Placides] (He asked me to give him credit)

**Comment by LorgeN** [comment]
> High tier items only keep their value until they are broken, and no amount of money can repair them. This is frustrating because people cannot keep their high tier items, such as prot 10 armor or tier 5 crate armor.

This is quite literally the point of this change. Thank you for confirming that it is working.

> I think items should be able to be repaired with no chance of enchantment loss at spawn via a sign. Right-clicking this sign would charge 1.5 million tokens, but completely restore the durability of an item.

You yourself have said that 1.5 million tokens is "nothing".

> I know that the p10 kit is being buffed for this reason, but I think there needs to be an option to repair armor in some way, even if it costs a significant amount of tokens.

No, not for this reason. Extending the lifetime of an item somewhat and making it infinite is far from the same.
