### ISSUE TITLE
Ender aura - Eye of ender dissapearing

### ISSUE THREAD

**Issue by Adrianturbo** [LorgeN/CrazyWars-Issues#127]
After right-clicking with the **eye of ender**, there is no way to tell how long the cooldown is until you can use it again. After use, and you right-click with it, it disappears, like "when you are looking for the end portal."
This leads to loss of the Eye of ender, and you will not be able to get one back until the kit is ready.

**Comment by LorgeN** [comment]
Please resubmit this report on the forums: https://crazywars.me/forums/reportbug/
