### ISSUE TITLE
Advent Crates Mad Lad Kit Items not granting

### ISSUE THREAD

**Issue by zulater** [LorgeN/CrazyWars-Issues#128]
**Minecraft Username**
zulater

**What is this about?**
Advent crate (possibly more?) not able to easily test more

**To Reproduce**
win Mad Lad Kit Items from advent calendar crate

**What happens?**
You are not granted any items

**What should happen?**
Mad Lad Kit Items should be put in your inventory

**Additional context**
Several people have had the issue so it is repeatable

**Comment by MemelordGod** [comment]
I have a recording of this issue if that is helpful at all

**Comment by LorgeN** [comment]
Fixed.
