### ISSUE TITLE
Ore mines not using all there fuel

### ISSUE THREAD

**Issue by AlexRCASI** [LorgeN/CrazyWars-Issues#130]
**Minecraft Username**
AlexRCASI

**What is this about?**
Skyblock
**To Reproduce**
Steps to reproduce the behavior

**What happens?**
it dosent use all the fuel and it just stays on 1.66m
**What should happen?**
i expected it to run all the way out and use all of its fuel
**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.
u can try it for yourself it will stop on 1.66m
**Additional context**
None

**Comment by LorgeN** [comment]
There is a time limit on how long it can generate before you have to redeem. I will make this more clear in the UI.
