### ISSUE TITLE
Block Grinder Quest

### ISSUE THREAD

**Issue by Blindshot59** [LorgeN/CrazyWars-Issues#19]
**Minecraft Username**
Blindshot59

**What is this about?**
The Block grinder quest 

**To Reproduce**
Reach the quest to Buy a block grinder.

**What happens?**
Either you buy it, and it doesn't sign it off (Reported by Dynn7)
Or you get up to needing to fuel it, and no amount of fuel signs off the quest. (Jug624)

**What should happen?**
The quest is completed smoothly.

**Comment by Blindshot59** [comment]
https://youtu.be/tt2z8_MK3G8

**Comment by LorgeN** [comment]
@Blindshot59 If the objective is to refuel the Cobblestone Generator, refueling the Block Grinder wont really help...
