### ISSUE TITLE
Particles left after building is "accepted"

### ISSUE THREAD

**Issue by zulater** [LorgeN/CrazyWars-Issues#21]
**Minecraft Username**
zulater (reporting for iWoodGames)

**What is this about?**
Island, placing building

**To Reproduce**
Unknown.

**What happens?**
Building was placed and the particles to show the outline remained after user clicked "accept"

**What should happen?**
They should go away as normal

**Screenshots/Videos**
https://youtu.be/W1nkHjREfMM

**Additional context**
I removed the building and re-built it, particles stayed, tried upgrading, particles stayed

**Comment by Geeeekoid** [comment]
To reproduce: 
Place 2 buildings then click accept twice, and the particles for the first one placed will stay
