### ISSUE TITLE
Item Transporter not seeing chests

### ISSUE THREAD

**Issue by zulater** [LorgeN/CrazyWars-Issues#23]
**Minecraft Username**
zulater

**What is this about?**
Skyblock Item Transporter

**To Reproduce**
Usually the first item transporter does this (no consumer to choose) but I've had more recent ones like the 5th/6th one having the same issue.  Also doesn't seem to see chests on a higher level (one that started to work).

**What happens?**
Unable to select item consumer or producer

**What should happen?**
Select producer/consumer

**Screenshots/Videos**
Better full video with info and building info at same time: https://youtu.be/033IVEuf8A0

Backup videos:
https://youtu.be/vJlBPo76nc4
https://youtu.be/0PxWnjJ_dm4

**Additional context**

**Comment by LorgeN** [comment]
Added checks to hopefully resolve the issue
