### ISSUE TITLE
Xp Tank Level Reset

### ISSUE THREAD

**Issue by Blindshot59** [LorgeN/CrazyWars-Issues#26]
**Minecraft Username**
Blindshot59

**What is this about?**
The XP Tank Building

**To Reproduce**
Have one or more XP Tanks on your island

**What happens?**
AFter time they reset back to level 1, allowing you to upgrade again, giving you all the same Island xp again.

**What should happen?**
They remain whatever level you left them at

**Screenshots**
<img width="981" alt="2019-09-16_08 55 25" src="https://user-images.githubusercontent.com/55067673/64928758-dfd0b300-d85f-11e9-8bcd-43956d2a3a1a.png">
Just noticed it ^
<img width="1001" alt="2019-09-17_07 55 15" src="https://user-images.githubusercontent.com/55067673/64996204-a90ea180-d920-11e9-80c7-46f95a98d764.png">
Noticed again, (Checked just after a restart)
<img width="1014" alt="2019-09-19_19 27 32" src="https://user-images.githubusercontent.com/55067673/65231975-bc359300-db13-11e9-8178-333884e0a849.png">
Noticed again^

**Comment by LorgeN** [comment]
Could potentially be related to the no-change upgrade system
