### ISSUE TITLE
Suffix Bug

### ISSUE THREAD

**Issue by Bigbear1313** [LorgeN/CrazyWars-Issues#27]
**Minecraft Username**
Bigbear1313
**What is this about?**
Suffixes
**To Reproduce**
You have to equip a custom suffix, then you unequip it whenever, then when you look at /suffixes again, all of you custom and unique suffixes disappear.
**What happens?**
You lose all your custom and unique suffixes.
**What should happen?**
You shouldn't lost all of your custom and unique suffixes once you unequip one.
**Screenshots/Videos**
https://youtu.be/Byy-Ispxz78
**Additional context**

**Comment by LorgeN** [comment]
Wasn't loading custom suffixes if no selected suffix existed. Easy fix, no data loss.
