### ISSUE TITLE
Cobblestone Generator, consuming fuel without creating blocks, not accepting fuel

### ISSUE THREAD

**Issue by zulater** [LorgeN/CrazyWars-Issues#28]
**Minecraft Username**
zulater

**What is this about?**
Skyblock, Cobblestone Generator

**To Reproduce** / **What happens?**
2 things
1, let it generate the max 120 cobble.  Once there it will continue to consume fuel till it runs out
2, It would take fuel but not reach "full" or even increase.

**What should happen?**
1, if it's not generating and has reached capacity it should stop using fuel (difficult maybe)
2, it should accept fuel and increase the "tank"

**Screenshots/Videos**
https://youtu.be/TcpjgxAUwsw

**Comment by LorgeN** [comment]
This is simply a graphical glitch. If you redeem the items, it wont consume for more than what it should. I will see what I can do about the UI, but it isn't actually causing any harm.

**Comment by LorgeN** [comment]
Potentially fixed this, but I might have also broken other stuff. Will have to test.
