### ISSUE TITLE
Blaze Issue (Holy Torch)

### ISSUE THREAD

**Issue by Mixeq** [LorgeN/CrazyWars-Issues#3]
**Minecraft Username**
Mixeq

**What is this about?**
SkyBlock Islands

**To Reproduce**
Spawn a blaze and fuel a holy torch- the Blaze must be within the radius of the torch

**What happens?**
The Blaze dies without dropping Blaze Rods

**What should happen?**
The Blazes should drop Blaze Rods upon death

**Screenshots/Videos**
N/A

**Additional context**
N/A

**Comment by LorgeN** [comment]
There really isn't much to do here. It may be a default Minecraft mechanic for Blazes not to drop items when killed by a non-entity. I have not explicitly disabled drops for blazes in any way.
