### ISSUE TITLE
Attack O Mat Mechanic

### ISSUE THREAD

**Issue by Mixeq** [LorgeN/CrazyWars-Issues#37]
**Is your feature request related to a problem? Please describe.**
Island Guardian behavior is very strange when the guardian is able to move around in a non-confined area. I'm fully aware that island guardian behavior is very difficult to code for, I just think this would help minimalize problems that come with it.

**Describe the solution you'd like**
When attacking an island, the attack o mat that is under attack would be completely surrounded with blocks. These could be barriers or blocks that fit with the same scheme as the mat itself, such as stone brick or nether brick. Once the guardian is defeated, the barrier would lift and players would be free to explore the island. This fixes instances where one player camps a certain area of the island while the other kills the guardian, and then the camping player gets more use than normal of the 60 second timer. This also fixes unfairly trapping the guardian with blocks, and fixes the guardians randomly flying away.

**Describe alternatives you've considered**
Re coding island guardian behavior (this is unrealistic based on how complex it is)
Disabling block placement until the guardian is defeated 

**Additional context**

**Comment by LorgeN** [comment]
Again, see my response to #36
