### ISSUE TITLE
Market place blocks missing

### ISSUE THREAD

**Issue by ProDragonPvP** [LorgeN/CrazyWars-Issues#42]
**Minecraft Username**
ProDragon_PvP

**What is this about?**
Skyblock market place

**To Reproduce**
Place a marketplace building

**What happens?**
2 of the front blocks wont change into the block they are supposed to change in

**What should happen?**
Those 2 blocks should change just like the rest of the blocks

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/55764205/65544050-c0e2b880-df12-11e9-98d7-ba93f961b9df.png)

**Additional context**
This issue has been here from the start its not a big issue just a annoying one

**Comment by LorgeN** [comment]
That is part of the build, and is fully intentional. Have you ever seen perfectly square gravel in real life?
