### ISSUE TITLE
Bucket Removal

### ISSUE THREAD

**Issue by Mixeq** [LorgeN/CrazyWars-Issues#5]
**Is your feature request related to a problem? Please describe.**
While trying to place a platform for a beacon, I noticed that every ore blocks I place turns into a bucket of [ore name]

**Describe the solution you'd like**
I think the bucket should be removed entirely.

**Describe alternatives you've considered**
I think this could also be fixed by limiting the island to have only one bucket (for each ore) total, that way you could have the bucket perk and the ore block perk. Not sure if that's too much work or not, that's why it's listed here instead of my primary suggestion.

**Additional context**
N/A

**Comment by LorgeN** [comment]
barrel*
