### ISSUE TITLE
TimeLord Kit Buff

### ISSUE THREAD

**Issue by Mixeq** [LorgeN/CrazyWars-Issues#61]
**Is your feature request related to a problem? Please describe.**
The timelord kit was designed when the simultaneous buildings cap was higher, and the kit is now extremely devalued.

**Describe the solution you'd like**
I think that the simultaneous buildings cap should be raisable to 10. This number is high enough to do building in bulk, but not so high that the server would suffer intensely from lag.

**Describe alternatives you've considered**
I've also considered making the cooldown shorter, but I feel like this defeats the purpose of the kit- if you can speed up buildings at a semi frequent rate then the kit is just slightly cheaper than speeding up the buildings with tokens.

**Additional context**
None

**Comment by LorgeN** [comment]
Increased to 8.
