### ISSUE TITLE
Island Invite Command 

### ISSUE THREAD

**Issue by Mixeq** [LorgeN/CrazyWars-Issues#63]
**Is your feature request related to a problem? Please describe.**
You're able to send island invites to people who already have an island.

**Describe the solution you'd like**
If someone sends an invite request to a player who is already a part of an island, the resulting text should be something along the lines of "this player is already part of an island! They must leave in order to receive invites."

**Describe alternatives you've considered**
None 
**Additional context**
None

**Comment by LorgeN** [comment]
While I considered this option, I didn't really see it as necessary because the person receiving the invite will get this error message. You can check if someone has an island using /is show <player>, so for now I am not going to spend any time on this.
