### ISSUE TITLE
Dying with special items while attacking leaves a broken copy in attack-o-mat chest

### ISSUE THREAD

**Issue by wzhouruize** [LorgeN/CrazyWars-Issues#65]
Anachronistical

Islands Attacking

To reproduce, attack an island with a special item (ender aura, frost staff, etc.) and die. This will leave a chest with everything you had including a broken copy of the special item. People sell these on the auction house or through trades, scamming other people who don't know that special items are normally untradeable. 

The item should delete and not be placed into the chest.

**Comment by LorgeN** [comment]
Are you sure you just don't have the kits? Or are you trying to use it on your island?

You need to have the kit to actually use it.
