### ISSUE TITLE
Creative Plots WorldEdit

### ISSUE THREAD

**Issue by Mixeq** [LorgeN/CrazyWars-Issues#67]
**Minecraft Username**
Mixeq

**What is this about?**
Creative Plots

**To Reproduce**
Use a worldedit command that reaches out of one plot you own, given that you own the surrounding plots.

**What happens?**
The command happens to all of the plots that the command reaches, (ex: //sphere 100 quartz)

**What should happen?**
The command should only work inside of the plot it was executed on

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/55066410/66265021-f4f09000-e7d4-11e9-80dc-08cc0b9fb79d.png)

**Additional context**
None

**Comment by LorgeN** [comment]
Not a bug. Don't be stupid when using WorldEdit.
