### ISSUE TITLE
/trash combat tag

### ISSUE THREAD

**Issue by Mixeq** [LorgeN/CrazyWars-Issues#69]
**Is your feature request related to a problem? Please describe.**
When in a fight, a player can choose to /trash his/her items before he/she is killed. This has been reported as a bug a few times on the discord channel by a few players.

**Describe the solution you'd like**
I think that the /trash menu should have a "dump" button that takes 3 seconds to delete the items within the trash GUI.
**Describe alternatives you've considered**
Limiting /trash so that you cannot use it while in combat (too annoying for players)
4 second combat cooldown (Likely more work coding than what it's worth, and still annoying)

**Additional context**
None

**Comment by LorgeN** [comment]
Will disable /trash in combat. Everything else is more work than I care to do for this little of a problem.
