### ISSUE TITLE
Spawners Stacking

### ISSUE THREAD

**Issue by FlameShine11** [LorgeN/CrazyWars-Issues#7]
FlameShine_11
SkyBlock Islands
Placing mob spawner (in this case cave spider spawners) next to each other
The spawners "stack" and when using silk to remove only receive 1 spawner back
The spawners should place individually and/or receive same amount of spawners when removed
![CaveSpider](https://user-images.githubusercontent.com/55103399/64551498-21fb7100-d303-11e9-862b-9bf604b51b78.JPG)
![CaveSpider1](https://user-images.githubusercontent.com/55103399/64551547-3c354f00-d303-11e9-854f-e7c4d4b8fb2e.JPG)

**Comment by zulater** [comment]
https://youtu.be/HyuDUIyyMEQ
Video backup to what Flame is mentioning.

**Comment by LorgeN** [comment]
Caused by local silk spawners overriding WildStacker. Added check to see if WildStacker was handling the spawner stack, and escaped event if so.
