### ISSUE TITLE
XP tank at low y levels (0-1) cannot be upgraded

### ISSUE THREAD

**Issue by zulater** [LorgeN/CrazyWars-Issues#79]
**Minecraft Username**
zulater

**What is this about?**
Skyblock XP tank

**To Reproduce**
Build XP tank at like level 0 or 1 (2 might work as well)

**What happens?**
You can place it but not upgrade it.  You get a "upgrading interferes with world height limit" even though the xp tank does not change size

**What should happen?**
You should be able to upgrade it

**Screenshots/Videos**
https://youtu.be/wDDj16mpzVQ

**Comment by LorgeN** [comment]
Could potentially be using schem size and not computed building size. Will see what I can do.
