### ISSUE TITLE
Potion Stacking Bug

### ISSUE THREAD

**Issue by Originatings** [LorgeN/CrazyWars-Issues#80]
**Minecraft Username**
Originatings

**What is this about?**
Islands

**To Reproduce**
Collect the wizard kit twice. Drag one stack of the same potion onto the other

**What happens?**
The 2 stacks of 2 turn into one stack of 3 and a single potion. They can be stacked further, up to 64 if you have enough potions.

**What should happen?**
Nothing should happen, they should stay 2 stacked.

**Screenshots/Videos**
https://youtu.be/t0cBw2qbaj8
**Additional context**
None

**Comment by LorgeN** [comment]
Will make the wizard kit not have stacked potions at all.
