### ISSUE TITLE
Speed Glitch

### ISSUE THREAD

**Issue by zulater** [LorgeN/CrazyWars-Issues#81]
**Minecraft Username**
zulater (for LegendPerplex)

**What is this about?**
Skyblock system speed glitch

**To Reproduce**
Be on your island with speed 3 tower, interact with npc then do /mr and you can have perm speed 3

**What happens?**
You get perm speed 3

**What should happen?**
Speed 3 should clear when you leave your island

**Screenshots/Videos**
https://www.youtube.com/watch?v=5oSpNYnaMsY&feature=youtu.be

**Comment by LorgeN** [comment]
Will remove any effect that is over infinite threshold on load. Should resolve this and other similar issues.
