### ISSUE TITLE
Ender Kit Pearl Timer

### ISSUE THREAD

**Issue by Mixeq** [LorgeN/CrazyWars-Issues#88]
**Minecraft Username**
Mixeq

**What is this about?**
Battlegrounds Ender Kit

**To Reproduce**
Throw a pearl and go invisible before it lands, or throw a pearl while invisible.

**What happens?**
The pearl is stopped because you aren't able to use it while invisible, but the cooldown is reset.

**What should happen?**
The cooldown should not reset, so you are able to pearl again after you are invisible (without waiting for the cooldown)

**Screenshots/Videos**
None

**Additional context**
None

**Comment by LorgeN** [comment]
That is intentional. Don't be a dumbdumb.

**Comment by Mixeq** [comment]
The cooldown reset is intentional? I thought the intent was to stop people from using pearls while invisible

**Comment by LorgeN** [comment]
1. Please stop saying "cooldown is reset" when you mean "cooldown begins". 2. Yes, that is fine. Don't be a dumbdumb and throw pearls like that.

**Comment by Mixeq** [comment]
Okay, sorry for the miswording, just felt like a reset since I didn't actually use a pearl and the cooldown was started again. Thanks for the clarification.
