### ISSUE TITLE
Stained Clay in Block Grinder

### ISSUE THREAD

**Issue by Blindshot59** [LorgeN/CrazyWars-Issues#9]
**Minecraft Username**
Blindshot59

**What is this about?**
Mining Stained clay using the block grinder.

**To Reproduce**
Set your block grinder to any colour of stained clay

**What happens?**
It gives you white stained clay instead of the chosen colour

*What should happen?**
You're given the colour you mine

**Video**
https://youtu.be/efONGQq_9Xw

**Comment by LorgeN** [comment]
Did you have silk touch on that pickaxe?

**Comment by Blindshot59** [comment]
Yes I did

**Comment by LorgeN** [comment]
In that case the issue has been resolved
