### ISSUE TITLE
Item Transporter only lets you get one.

### ISSUE THREAD

**Issue by kokoPvP** [LorgeN/CrazyWars-Issues#90]
**Minecraft Username**
kokoPvP

**What is this about?**
Islands

**To Reproduce**
Sometimes the item transporter only alows you to get one item transporter.

**What happens?**
When you do this you only get one item transporter.

**What should happen?**
You should be able to get more then one item transporter

**Screenshots/Videos**
https://media.discordapp.net/attachments/570099204739956736/634536827511898152/Screenshot_161.png?width=1202&height=676

**Comment by LorgeN** [comment]
There's an overall building limit on your island. Please at least ask on Discord before posting stuff like this.
