### ISSUE TITLE
Crate glitch / inconsistency error

### ISSUE THREAD

**Issue by TomIsTheHunter** [LorgeN/CrazyWars-Issues#91]
**Minecraft Username**
TomIsAHunter

**What is this about?**
Crates

**To Reproduce**
Type /crate and look around, it's impossible to miss

**What happens?**
You will notice Kit and also Rank crates

**What should happen?**
Since "Rank" crates are unobtainable (as of now) the rank crate shouldn't be a valid crate option

**Screenshots/Videos**
![2019-10-18_16 32 47](https://user-images.githubusercontent.com/44981491/67103170-f488c980-f1c4-11e9-8951-0aba0558b44e.png)
![2019-10-18_16 32 48](https://user-images.githubusercontent.com/44981491/67103172-f488c980-f1c4-11e9-8680-a2266dcb2fe1.png)

**Comment by LorgeN** [comment]
Dumbdumb
