### ISSUE TITLE
Islands Balancing Suggestion 

### ISSUE THREAD

**Issue by Mixeq** [LorgeN/CrazyWars-Issues#99]
**Is your feature request related to a problem? Please describe.**
Islands are unfairly stacked to favor players who start early, or who play during a 6x booster. Players who played early game when there were often 6x boosters in effect have a high level, much higher than a player who started without one. Now that the season has progressed, 6x boosters are rare, and players who are starting out will level up slower. Even if a player has double the island value of another who played during a 6x boost, all that will happen is the player who started without the boost will hit a standstill in terms of progression sooner. Say one player places all of their token generators during a 6x boost, and another player without a boost. The player with the 6x multiplier will level up more and have a higher number of possible generators to place, whereas the unboosted player simply won't have the same number, even if they spent the same amount. In turn they will make less money, and progress slower. New players who join quite literally cannot beat the players who were here at the start, which is a big issue in terms of server expansion. If a player can't catch up to someone who doesn't even play anymore, it's very demotivating and uninviting to keep playing.

**Describe the solution you'd like**
Although these may seem extreme, I think these suggestions will fix an underlying issue that has been present for a while

1. Make island level based on value instead of xp.

This would take a lot of work to do, requiring a modifying of a few quests, and a revamped leveling system, but it sets up the next few suggestions. This new leveling system would be done by value conversions, with value contributing to levels. It would get exponentially more expensive to level up, this way leveling is still not easy to do.

2. Make 6x boosters for tokens only, since island level does not exist anymore.

3. Calculate island top on value alone. 

4. Remove the building cap on every building (excluding shops), and make the cost scaling exponential. This would prevent players from having an extreme amount of any building. 

**Describe alternatives you've considered**
None

**Additional context**
I know these would take a lot of work to implement, but I think they are necessary to keep the server open to new players. Right now we have a fairly regular player base, and new players will never be able to compete. I personally experienced this last season, only marginally beating Mortem420, someone who quit the server. It took me months to beat an inactive player, I can only imagine how long it will take someone now to beat a player who comes on even weekly.

**Comment by LorgeN** [comment]
This has to be one of the dumbest things I've ever read. You want me to remove the entire point of the 6x booster? Delete systems I spent so much time fine tuning? Redo about 250h of work? No.
